### ISSUE TITLE
Obtain embedding vectors

### ISSUE THREAD

**Issue by rominaappierdo** [mim-solutions/bert_for_longer_texts#1]
Hello and thank you for sharing your work!
I would like to know if there is a way to obtain embedding vectors of one (or more) sentences fed into the model.
Hope you could help me. 
Thank you in any case

**Comment by MichalBrzozowski91** [comment]
Hi, thanks for feedback. Can you elaborate what is your use case? So far we have implemented support for longer sequences for the binary classification problem.

**Comment by rominaappierdo** [comment]
Thank you for your reply, I just wanted to know if there was a way to simply obtain embedding vectors. I would like to just obtain a representation vector for a given (longer) sequence, no need to perform downstream tasks currently. Is it possible to obtain them with your work?

**Comment by MichalBrzozowski91** [comment]
Hi, I was working on it and I think it is possible to obtain embedding vectors using our code. I created a PR with [example notebook](https://github.com/mim-solutions/roberta_for_longer_texts/blob/add-notebook-with-getting-embedding-vectors/ipython/example_get_embedding_vectors.ipynb).
Feel free to ask any questions.
I hope it will help you.

**Comment by MichalBrzozowski91** [comment]
HI, we made major changes in this repo. Now in order to obtain embedding vectors, we suggest getting the tokenized chunks from the method `_tokenize` of the class `BertClassifierWithPooling`. The obtained tokens can then be directly fed to the pre-trained BERT to obtain embeddings of each chunk.
