### ISSUE TITLE
QnA system using BERT

### ISSUE THREAD

**Issue by Amrutha1101** [mim-solutions/bert_for_longer_texts#15]
I'm trying to build a QnA system with bert where i will provide a pdf document. As 512 token is the limitation it's unable to take longer texts like a pdf.
I want to know which part of this repository I need to use for bert to work fine even with pdf.

**Comment by Amrutha1101** [comment]
I'm a beginner your help would be greatly appreciated

**Comment by mwachnicki** [comment]
I recommend using `BertClassifierWithPooling`.
You can find a simple example in [this notebook](https://github.com/mim-solutions/bert_for_longer_texts/blob/main/notebooks/example_model_with_pooling_fit_predict.ipynb) and an extended description in [this file](https://github.com/mim-solutions/bert_for_longer_texts/blob/main/docs/bert_for_longer_texts.md).
