### ISSUE TITLE
plz help me 

### ISSUE THREAD

**Issue by cwoonb** [mim-solutions/bert_for_longer_texts#26]
1. Is there a method for multi-class classification?

2. Are you currently conducting research on multi-class classification?

3. I get this warning message when training the model: "Token indices sequence length is longer than the specified maximum sequence length for this model (23716 > 512). Running this sequence through the model will result in indexing errors." Does this warning not affect the model training?

**Comment by MichalBrzozowski91** [comment]
1, 2: At the moment no, but feel free to add a Pull Request. :)
3: The warning is expected.
You can also consult a Medium tutorial here: https://medium.com/p/299f1533b976
